version: '3'
services:
  app:
    build: .
    environment:
      - NODE_ENV=production
    links:
      - db
    ports:
      - '8080:8080'
  db:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
